namespace GameMU.EventManager.Services;

/// <summary>Mot tinh nang/su kien cua GameServer va cac file XML no su dung.</summary>
public record FeatureItem(string Category, string Feature, string Manager, string[] Xmls);

/// <summary>
/// Ban do Tinh nang -> File XML, sinh tu viec scan ma nguon GameServer (thu muc Logic/, Server/Data/).
/// Moi dong = mot lop quan ly (manager) + danh sach file XML trong GameRes/Config ma no doc.
/// </summary>
public static class FeatureCatalog
{
    public static readonly List<FeatureItem> Items = new()
    {
        new("Bang hội", "Giải đấu bang hội (League)", "Logic/BangHuiMatchManager.cs", new[]{ "LeagueBirthPoint.xml", "LeagueMatch.xml", "LeagueNewAward.xml", "LeagueNewRandom.xml", "LeagueOpen.xml", "LeagueSuperAward.xml", "LeagueSuperList.xml", "LeagueSustain.xml", "LeagueWar.xml" }),
        new("Bang hội", "Quân đoàn (Legion)", "Logic/JunTuanManager.cs", new[]{ "LegionTasks.xml", "LegionsManager.xml", "systemparams.xml" }),
        new("Bang hội", "Thần điện liên minh", "Logic/UnionPalace/UnionPalaceManager.cs", new[]{ "ShenDianExtra.xml", "ShenDianLevelUp.xml", "ShenDianScale.xml" }),
        new("Bang hội", "Đại chiến quân đoàn (Karen)", "Logic/KarenBattleManager.cs", new[]{ "LegionsWar.xml" }),
        new("Bản đồ", "Bản đồ / Cổng dịch chuyển / Vùng an toàn", "Logic/GameMap.cs", new[]{ "MapConfig.xml" }),
        new("Chuyển sinh", "Thánh ấn chuyển sinh", "Logic/Reborn/RebornStampConsts.cs", new[]{ "ShenShengYinJiZhu.xml", "ShenShengYinJiZi.xml" }),
        new("Chuyển sinh", "Trang bị chuyển sinh", "Logic/Reborn/RebornEquipConst.cs", new[]{ "EquipQuenching.xml", "RebornEquip.xml", "RebornEquipEvolution.xml", "RebornSuperiorDrop.xml", "RebornSuperiorType.xml" }),
        new("Cánh", "Chú linh chú hồn (MU Wings)", "Logic/MUWings/ZhuLingZhuHunManager.cs", new[]{ "MaxWinZhuLing.xml", "WinZhuLing.xml", "ZhuLingType.xml" }),
        new("Công thành", "Công thành chiến (LuoLan)", "Logic/LuoLanChengZhanManager.cs", new[]{ "QiZuoConfig.xml", "SiegeWarfare.xml", "SiegeWarfareBirthPoint.xml", "SiegeWarfareEveryDayAward.xml", "SiegeWarfareExp.xml" }),
        new("Công thành", "Lãnh địa / Thành chiến", "Logic/LangHunLingYuManager.cs", new[]{ "City.xml", "CityWar.xml", "CityWarQiZuo.xml", "SiegeWarfareBirthPoint.xml", "SiegeWarfareExp.xml" }),
        new("Hoạt động", "Hoạt động hằng ngày", "Logic/ActivityNew/EverydayActivity.cs", new[]{ "EveryDayActivity.xml", "EveryDayActivityGroup.xml", "EveryDayActivityType.xml" }),
        new("Hoạt động", "Hoạt động đặc biệt (gói ưu đãi theo đợt)", "Logic/ActivityNew/SpecialActivity.cs", new[]{ "SpecialActivity.xml", "SpecialActivityTime.xml" }),
        new("Hoạt động", "Trung tâm nạp hoạt động/sự kiện (lễ hội, nạp, gộp server...)", "Logic/HuodongCachingMgr.cs", new[]{ "ChengJiuFanLi.xml", "ChongZhiDuiHuan.xml", "ChongZhiSong.xml", "DaTianShiFanLi.xml", "DayChongZhi.xml", "HeFuDengLu.xml", "HeFuFanLi.xml", "HeFuLiBao.xml", "HeFuLuoLan.xml", "HeFuType.xml", "HeFuZhangChang.xml", "HuShenFuFanLi.xml", "HunYinFanLi.xml", "JieRiBaoXiang.xml", "JieRiChongZhiKing.xml", "JieRiDanBiChongZhi.xml", "JieRiDayChongZhi.xml", "JieRiDengLu.xml", "JieRiDuoBei.xml", "JieRiFuWenFanLi.xml", "JieRiHuiJiFanLi.xml", "JieRiLeiJi.xml", "JieRiLeiJiXiaoFei.xml", "JieRiLiBao.xml", "JieRiMeiRiLeiJi.xml", "JieRiVip.xml", "JieRiXiaoFeiKing.xml", "JunXianFanLi.xml", "MuJieRiType.xml", "NewDig2.xml", "PKJiangLi.xml", "QiangHuaFanLi.xml", "ShenZhuangAward.xml", "ThemeActivityOpen.xml", "ThemeActivityType.xml", "VIPFanLi.xml", "WangChengJiangLi.xml", "WingFanLi.xml", "ZhuiJiaFanLi.xml" }),
        new("Hằng ngày", "Hôm nay (JianFu)", "Logic/Today/TodayManager.cs", new[]{ "JianFu.xml" }),
        new("Hệ thống", "Giftcode", "Logic/GiftCodeNewManager.cs", new[]{ "GiftCodeNew.xml" }),
        new("Hệ thống", "Mở hệ thống theo phiên bản (IsOpen)", "Logic/VersionSystemOpenManager.cs", new[]{ "VersionSystemOpen.xml" }),
        new("Hồi quy", "Hoạt động hồi quy - Mở", "Logic/RegressActiveOpen.cs", new[]{ "HuiGuiHuoDong.xml" }),
        new("Khác", "AlchemyManager", "Logic/AlchemyManager.cs", new[]{ "CurrencyConversion.xml" }),
        new("Khác", "AllThingsCalcItem", "Logic/AllThingsCalcItem.cs", new[]{ "QiangHuaFuJia.xml" }),
        new("Khác", "CGetOldResourceManager", "Logic/CGetOldResourceManager.cs", new[]{ "ZiYuanZhaoHui.xml" }),
        new("Khác", "ChuanQiQianHua", "Logic/ChuanQiQianHua.cs", new[]{ "QiangHua.xml" }),
        new("Khác", "CompBattleRuntimeData", "Logic/CompBattleRuntimeData.cs", new[]{ "ForceCraft.xml", "ForceCraftBirth.xml", "ForceCraftReward.xml", "ForceStronghold.xml" }),
        new("Khác", "CompMineRuntimeData", "Logic/CompMineRuntimeData.cs", new[]{ "CompMineAward.xml", "CompMineBirthPoint.xml", "CompMineLink.xml", "CompMineTruck.xml", "CompMineWar.xml" }),
        new("Khác", "CompRuntimeData", "Logic/CompRuntimeData.cs", new[]{ "Comp.xml", "CompLevel.xml", "CompNotice.xml", "CompResources.xml", "CompSolder.xml", "CompSolderSite.xml" }),
        new("Khác", "DanBiChongZhiActivity", "Logic/DanBiChongZhiActivity.cs", new[]{ "JieRiDanBiChongZhi.xml" }),
        new("Khác", "Data", "Logic/Data.cs", new[]{ "ChannelName.xml", "ExtPropThreshold.xml", "RebornLianZhan.xml", "Settings.xml" }),
        new("Khác", "DeControl", "Logic/DeControl.cs", new[]{ "DeControl.xml" }),
        new("Khác", "EquipUpgradeCacheMgr", "Logic/EquipUpgradeCacheMgr.cs", new[]{ "EquipUpgrade.xml" }),
        new("Khác", "FaceBookManager", "Logic/FaceBookManager.cs", new[]{ "FacebookAward.xml" }),
        new("Khác", "FluorescentGemDefine", "Server/Data/FluorescentGemDefine.cs", new[]{ "GemDig.xml", "GemDigType.xml", "GemLevelup.xml" }),
        new("Khác", "GMCommands", "Logic/GMCommands.cs", new[]{ "TeQuanTiaoJian.xml" }),
        new("Khác", "Global", "Logic/Global.cs", new[]{ "EveryDayActivity.xml", "Goods.xml", "GoodsQuality.xml", "HorseBaseProp.xml", "HorseJiFen.xml", "HorsePropLimit.xml", "HorseUp.xml", "JingMai.xml", "LevelUp.xml", "MuJieRiType.xml", "QualityUp.xml", "Settings.xml", "SpecialActivity.xml", "SpecialActivityTime.xml", "TeQuanBoss.xml", "TeQuanBuff.xml", "TeQuanChouJiang.xml", "TeQuanHongBao.xml", "TeQuanJiHuo.xml", "TeQuanJiangLi.xml", "TeQuanShangCheng.xml", "TeQuanTiaoJian.xml", "TeQuanZhiGou.xml", "ThemeActivityType.xml", "VIP.xml", "npcs.xml" }),
        new("Khác", "GoldAuctionConfigModel", "Logic/GoldAuction/GoldAuctionConfigModel.cs", new[]{ "AngelTempleAuctionAward.xml", "Auction.xml" }),
        new("Khác", "GongGaoDataManager", "Logic/GongGaoDataManager.cs", new[]{ "Gonggao.xml" }),
        new("Khác", "GoodsPackManager", "Logic/GoodsPackManager.cs", new[]{ "EraDropLimit.xml" }),
        new("Khác", "GoodsReplaceManager", "Logic/Goods/GoodsReplaceManager.cs", new[]{ "ReplaceGoods.xml" }),
        new("Khác", "GoodsUtil", "Logic/GoodsUtil.cs", new[]{ "GetGoods.xml" }),
        new("Khác", "GuardStatueConst", "Logic/TuJian/GuardStatueConst.cs", new[]{ "JingPoShouHu.xml", "ShouHuLevelUp.xml", "ShouHuSuitUp.xml", "TuJianShouHuType.xml" }),
        new("Khác", "HorseCachingManager", "Logic/HorseCachingManager.cs", new[]{ "HorseEnchance.xml" }),
        new("Khác", "InputFanLiNew", "Logic/ActivityNew/InputFanLiNew.cs", new[]{ "SanZhouNian_ChongZhiFanLi.xml" }),
        new("Khác", "JieRiCZQGActivity", "Logic/ActivityNew/JieRiCZQGActivity.cs", new[]{ "JieRiChongZhiQiangGou.xml" }),
        new("Khác", "JieRiChongZhiHongBaoActivity", "Logic/ActivityNew/JieRiChongZhiHongBaoActivity.cs", new[]{ "JieRiChongZhiHongBao.xml" }),
        new("Khác", "JieRiFuLiActivity", "Logic/ActivityNew/JieRiFuLiActivity.cs", new[]{ "JieRiFuLi.xml" }),
        new("Khác", "JieRiGiveKingActivity", "Logic/ActivityNew/JieRiGiveKingActivity.cs", new[]{ "JieRiZengSongKing.xml" }),
        new("Khác", "JieRiHongBaoActivity", "Logic/ActivityNew/JieRiHongBaoActivity.cs", new[]{ "JieRiQuanMinHongBao.xml" }),
        new("Khác", "JieRiRecvKingActivity", "Logic/ActivityNew/JieRiRecvKingActivity.cs", new[]{ "JieRiShouQuKing.xml" }),
        new("Khác", "JieriGiveActivity", "Logic/ActivityNew/JieriGiveActivity.cs", new[]{ "JieRiZengSong.xml" }),
        new("Khác", "JieriHongBaoKingActivity", "Logic/ActivityNew/JieriHongBaoKingActivity.cs", new[]{ "JieRiHongBaoBang.xml" }),
        new("Khác", "JieriIPointsExchgActivity", "Logic/ActivityNew/JieriIPointsExchgActivity.cs", new[]{ "ChongZhiDuiHuan.xml" }),
        new("Khác", "JieriLianXuChargeActivity", "Logic/ActivityNew/JieriLianXuChargeActivity.cs", new[]{ "JieRiLianXu.xml" }),
        new("Khác", "JieriPlatChargeKing", "Logic/ActivityNew/JieriPlatChargeKing.cs", new[]{ "PingTaiChongZhiKing.xml" }),
        new("Khác", "JieriPlatChargeKingEveryDay", "Logic/ActivityNew/JieriPlatChargeKingEveryDay.cs", new[]{ "JieRiMeiRiChongZhiWang.xml" }),
        new("Khác", "JieriRecvActivity", "Logic/ActivityNew/JieriRecvActivity.cs", new[]{ "JieRiShouQu.xml" }),
        new("Khác", "JieriSuperInputActivity", "Logic/ActivityNew/JieriSuperInputActivity.cs", new[]{ "MU_ChongZhiFanLi.xml" }),
        new("Khác", "JieriVIPYouHuiActivity", "Logic/ActivityNew/JieriVIPYouHuiActivity.cs", new[]{ "ChongZhiDuiHuan.xml", "VIPYouHuiLiBao.xml" }),
        new("Khác", "JueXingConsts", "Server/Data/JueXingConsts.cs", new[]{ "AwakenActivation.xml", "AwakenLevel.xml", "AwakenRecovery.xml", "AwakenSuit.xml" }),
        new("Khác", "JueXingManager", "Logic/JueXingManager.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "KarenBattleManager_MapEast", "Logic/KarenBattleManager_MapEast.cs", new[]{ "LegionsEast.xml", "LegionsEastBirthPoint.xml", "LegionsEastFlag.xml" }),
        new("Khác", "KarenBattleManager_MapWest", "Logic/KarenBattleManager_MapWest.cs", new[]{ "LegionsWest.xml", "LegionsWestBirthPoint.xml" }),
        new("Khác", "KuaFuMapManager", "Logic/KuaFuMapManager.cs", new[]{ "MapLine.xml" }),
        new("Khác", "LingDiCaiJiConsts", "Server/Data/LingDiCaiJiConsts.cs", new[]{ "ManorCollectMonster.xml" }),
        new("Khác", "MagicSwordManager", "Logic/MagicSword/MagicSwordManager.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "MarriageOtherLogic", "Logic/MarriageOtherLogic.cs", new[]{ "GiveRose.xml", "GoodWill.xml", "WeddingRing.xml" }),
        new("Khác", "MarryPartyLogic", "Logic/MarryPartyLogic.cs", new[]{ "WeddingFeasttAward.xml" }),
        new("Khác", "MazingerStoreConst", "Logic/MazingerStoreConst.cs", new[]{ "MoShenMiBaoJie.xml", "MoShenMiBaoXing.xml" }),
        new("Khác", "MerlinMagicBookDefine", "Server/Data/MerlinMagicBookDefine.cs", new[]{ "MagicBook.xml", "MagicBookStar.xml", "MagicWord.xml" }),
        new("Khác", "MoRiJudgeConsts", "Logic/MoRi/MoRiJudgeConsts.cs", new[]{ "MoRiShenPan.xml" }),
        new("Khác", "MonsterZone", "Logic/MonsterZone.cs", new[]{ "Monsters.xml" }),
        new("Khác", "MonsterZoneManager", "Logic/MonsterZoneManager.cs", new[]{ "Monsters.xml" }),
        new("Khác", "MountHolyStampConst", "Logic/MountHolyStampConst.cs", new[]{ "ShengYinShengJi.xml", "ShengYinTaoZhuang.xml", "ShengYinZhuoYue.xml" }),
        new("Khác", "NPCGeneralManager", "Logic/NPCGeneralManager.cs", new[]{ "npcs.xml" }),
        new("Khác", "NPCSaleList", "Logic/NPCSaleList.cs", new[]{ "NPCSaleList.xml" }),
        new("Khác", "OneDollarBuyActivity", "Logic/ActivityNew/OneDollarBuyActivity.cs", new[]{ "OneDollarBuy.xml" }),
        new("Khác", "OneDollarChongZhi", "Logic/ActivityNew/OneDollarChongZhi.cs", new[]{ "YiYuanChongZhi.xml" }),
        new("Khác", "PetSkillManager", "Logic/Goods/PetSkillManager.cs", new[]{ "PetSkill.xml", "PetSkillLevelup.xml" }),
        new("Khác", "PlatConfig", "Logic/PlatConfig.cs", new[]{ "PlatConfig.xml" }),
        new("Khác", "PopupWinMgr", "Logic/PopupWinMgr.cs", new[]{ "PopupWin.xml" }),
        new("Khác", "PrestigeMedalManager", "Logic/JingJiChang/PrestigeMedalManager.cs", new[]{ "ShengWangSpecialAttribute.xml", "ShengWangXunZhang.xml" }),
        new("Khác", "RebornDataConst", "Server/Data/RebornDataConst.cs", new[]{ "RebornBoss.xml", "RebornBossAward.xml", "RebornCombatForce.xml", "RebornLevel.xml", "RebornStage.xml" }),
        new("Khác", "RebornStoneConst", "Logic/RebornStoneConst.cs", new[]{ "ChongShengBaoShi.xml", "XuanCaiHeCheng.xml", "XuanCaiShuXing.xml", "ZhuangBeiDaKong.xml" }),
        new("Khác", "RegressActiveDayBuy", "Logic/RegressActiveDayBuy.cs", new[]{ "HuiGuiDayZhiGou.xml" }),
        new("Khác", "RegressActiveSignGift", "Logic/RegressActiveSignGift.cs", new[]{ "HuiGuiLoginNumGift.xml" }),
        new("Khác", "RegressActiveStore", "Logic/RegressActiveStore.cs", new[]{ "HuiGuiStore.xml" }),
        new("Khác", "RegressActiveTotalRecharge", "Logic/RegressActiveTotalRecharge.cs", new[]{ "HuiGuiChongZhiGift.xml" }),
        new("Khác", "ReloadXmlManager", "Logic/ReloadXmlManager.cs", new[]{ "ActivityTip.xml", "AngelTempleAuctionAward.xml", "AssConfig.xml", "AssInfo.xml", "AssList.xml", "Auction.xml", "CaiDaXiao.xml", "CaiShuZi.xml", "ChengJiu.xml", "ChengJiuBuff.xml", "DaiBiShiYong.xml", "DailyActiveAward.xml", "DailyActiveInfor.xml", "DuiHuanShangCheng.xml", "JieRiDanBiChongZhi.xml", "Lucky.xml", "LuckyAward.xml", "LuckyAward2.xml", "VipDailyAwards.xml", "activitytip.xml", "arenabattle.xml", "battle.xml", "battleaward.xml", "battleexp.xml", "bornname.xml", "chengjiu.xml", "chengjiubuff.xml", "chongzhi_andrid.xml", "chongzhi_app.xml", "chongzhi_yueyu.xml", "chongzhisong.xml", "dig.xml", "equipborn.xml", "equipupgrade.xml", "goods.xml", "goodspack.xml", "hefuqianggou.xml", "jingmai.xml", "lucky.xml", "luckyaward.xml", "npcsalelist.xml", "npcscripts.xml", "platconfig.xml", "popupwin.xml", "qizhengegoods.xml", "rebirth.xml", "systemopen.xml", "systemoperations.xml", "systemparams.xml", "vip.xml", "vipdailyawards.xml", "wuxue.xml", "zuanhuang.xml" }),
        new("Khác", "RobotTaskValidator", "Logic/RobotTaskValidator.cs", new[]{ "AssConfig.xml", "AssInfo.xml", "AssList.xml" }),
        new("Khác", "RoleManager", "Logic/RoleManager.cs", new[]{ "Settings.xml" }),
        new("Khác", "SevenDayBuyAct", "Logic/ActivityNew/SevenDay/SevenDayBuyAct.cs", new[]{ "SevenDayQiangGou.xml" }),
        new("Khác", "SevenDayChargeAct", "Logic/ActivityNew/SevenDay/SevenDayChargeAct.cs", new[]{ "SevenDayChongZhi.xml" }),
        new("Khác", "SevenDayConsts", "Logic/ActivityNew/SevenDay/SevenDayConsts.cs", new[]{ "SevenDayChongZhi.xml", "SevenDayGoal.xml", "SevenDayLogin.xml", "SevenDayQiangGou.xml" }),
        new("Khác", "SevenDayGoalAct", "Logic/ActivityNew/SevenDay/SevenDayGoalAct.cs", new[]{ "SevenDayGoal.xml" }),
        new("Khác", "SevenDayLoginAct", "Logic/ActivityNew/SevenDay/SevenDayLoginAct.cs", new[]{ "SevenDayLogin.xml" }),
        new("Khác", "ShenQiConsts", "Server/Data/ShenQiConsts.cs", new[]{ "Artifact.xml", "God.xml", "Toughness.xml" }),
        new("Khác", "ShenShiConsts", "Server/Data/ShenShiConsts.cs", new[]{ "FuWen.xml", "FuWenGod.xml", "FuWenHole.xml", "FuWenPayRandom.xml", "FuWenRandom.xml", "HuoDongFuWenPayRandom.xml", "HuoDongFuWenRandom.xml" }),
        new("Khác", "ShenShiManager", "Logic/ShenShiManager.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "SoulStoneConsts", "Logic/FluorescentGem/SoulStoneConsts.cs", new[]{ "HunShi.xml", "HunShiExp.xml", "HunShiGoodsType.xml", "HunShiGroup.xml", "HunShiType.xml" }),
        new("Khác", "SpecPriorityActivity", "Logic/ActivityNew/SpecPriorityActivity.cs", new[]{ "TeQuanBoss.xml", "TeQuanBuff.xml", "TeQuanChouJiang.xml", "TeQuanHongBao.xml", "TeQuanJiHuo.xml", "TeQuanJiangLi.xml", "TeQuanShangCheng.xml", "TeQuanTiaoJian.xml", "TeQuanZhiGou.xml" }),
        new("Khác", "SummonerManager", "Logic/Summoner/SummonerManager.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "SystemParamsList", "Logic/SystemParamsList.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "ThemeActivityConfig", "Logic/ThemeActivityConfig.cs", new[]{ "ThemeActivityType.xml" }),
        new("Khác", "ThemeDaLiBaoActivity", "Logic/ActivityNew/ThemeDaLiBaoActivity.cs", new[]{ "ThemeActivityLiBao.xml" }),
        new("Khác", "ThemeDataConst", "Server/Data/ThemeDataConst.cs", new[]{ "ThemeActivityBOSS.xml", "ThemeActivityMoYu.xml", "ThemeActivityZhuanSheng.xml", "ThemeActivityZhuanShengReward.xml" }),
        new("Khác", "ThemeDuiHuanActivity", "Logic/ActivityNew/ThemeDuiHuanActivity.cs", new[]{ "ThemeActivityDuiHuan.xml" }),
        new("Khác", "ThemeZhiGouActivity", "Logic/ActivityNew/ThemeZhiGouActivity.cs", new[]{ "OneDollarBuy.xml", "ThemeActivityZhiGou.xml" }),
        new("Khác", "TimerBossManager", "Logic/RefreshIconState/TimerBossManager.cs", new[]{ "BossInfo.xml", "HuangJin.xml" }),
        new("Khác", "TradeBlackManager", "Logic/CheatGuard/TradeBlackManager.cs", new[]{ "Blacklist.xml", "TradeConfig.xml" }),
        new("Khác", "UserActivateManager", "Logic/UserActivate/UserActivateManager.cs", new[]{ "SystemParams.xml" }),
        new("Khác", "VideoLogic", "Logic/VideoLogic.cs", new[]{ "Viedo.xml" }),
        new("Khác", "WebOldPlayerManager", "Logic/WebOldPlayerManager.cs", new[]{ "WebOldPlayer.xml" }),
        new("Khác", "WuXingMapMgr", "Logic/WuXingMapMgr.cs", new[]{ "WuXing.xml", "WuXingAwards.xml" }),
        new("Khác", "YaoSaiBossConsts", "Server/Data/YaoSaiBossConsts.cs", new[]{ "PetBoss.xml" }),
        new("Khác", "YaoSaiMissionConsts", "Server/Data/YaoSaiMissionConsts.cs", new[]{ "PetMission.xml" }),
        new("Khác", "YueKaManager", "Logic/YueKa/YueKaManager.cs", new[]{ "Card.xml" }),
        new("Khác", "ZhuanPanConsts", "Logic/ZhuanPan/ZhuanPanConsts.cs", new[]{ "ZhuanPan.xml", "ZhuanPanAward.xml" }),
        new("Khác", "ZuoQiConsts", "Server/Data/ZuoQiConsts.cs", new[]{ "HorseAdvanced.xml", "HorseArrayAddition.xml", "HorseEquipAddition.xml", "HorseFreeRandom.xml", "HorseLevelUp.xml", "HorsePayRandom.xml", "HorsePokedex.xml", "HorseRandom.xml", "HorseSuit.xml", "HorseSuperiorDrop.xml", "HorseSuperiorType.xml", "TeQuanHorseFreeRandom.xml", "TeQuanHorsePayRandom.xml", "TeQuanHorseRandom.xml" }),
        new("Khác", "ZuoQiManager", "Logic/ZuoQiManager.cs", new[]{ "SystemParams.xml" }),
        new("Kết hôn", "Phụ bản phu thê (BOSS)", "Logic/MarryFuBenMgr.cs", new[]{ "ManAndWifeBoss.xml" }),
        new("Kết hôn", "Đấu trường tình lữ", "Logic/Marriage/CoupleArena/CoupleAreanConsts.cs", new[]{ "CoupleBirthPoint.xml", "CoupleBuff.xml", "CoupleDuanWei.xml", "CoupleWar.xml", "CoupleWarAward.xml" }),
        new("Liên minh", "Chiến trường liên minh / Cứ điểm", "Logic/CompBattleManager.cs", new[]{ "ForceCraft.xml", "ForceCraftBirth.xml", "ForceCraftReward.xml", "ForceStronghold.xml" }),
        new("Liên minh", "Liên minh (Comp)", "Logic/CompManager.cs", new[]{ "Comp.xml", "CompLevel.xml", "CompNotice.xml", "CompResources.xml", "CompSolder.xml", "CompSolderSite.xml" }),
        new("Liên minh", "Mỏ liên minh", "Logic/CompMineManager.cs", new[]{ "CompMineAward.xml", "CompMineBirthPoint.xml", "CompMineLink.xml", "CompMineTruck.xml", "CompMineWar.xml" }),
        new("Liên server", "BOSS liên server", "Logic/KuaFuBossManager.cs", new[]{ "ThroughServiceBoss.xml", "ThroughServiceBossMonster.xml", "ThroughServiceBossRebirth.xml" }),
        new("Liên server", "Chiến trường dũng giả (xuyên server)", "Logic/YongZheZhanChangManager.cs", new[]{ "BattleCrystalMonster.xml", "BattleMonster.xml", "ThroughServiceBattle.xml", "ThroughServiceBattleAward.xml", "ThroughServiceRebirth.xml" }),
        new("Liên server", "Thập tự quân / Cướp tài nguyên liên server", "Logic/KuaFuLueDuoManager.cs", new[]{ "CrusadeBirthPoint.xml", "CrusadeCrystalMonster.xml", "CrusadeGroup.xml", "CrusadeQiZhi.xml", "CrusadeStore.xml", "CrusadeWar.xml" }),
        new("Liên server", "Tranh đoạt lãnh thổ", "Logic/ZhengDuoManager.cs", new[]{ "PlunderLands.xml", "PlunderLandsMonster.xml", "PlunderLandsRebirth.xml" }),
        new("Lãnh địa", "Thu thập lãnh địa", "Logic/LingDiCaiJiManager.cs", new[]{ "ShouWeiMonster.xml" }),
        new("Lãnh địa", "Xây dựng lãnh địa", "Logic/Building/BuildingManager.cs", new[]{ "Build.xml", "BuildLevel.xml", "BuildLevelAward.xml", "BuildTask.xml" }),
        new("Lãnh địa", "Yêu tái - Trang viên", "Logic/YaoSaiJianYuManager.cs", new[]{ "ManorCommand.xml", "ManorLevel.xml" }),
        new("Ngoại trang", "Biến thân (Transfiguration)", "Logic/BianShenManager.cs", new[]{ "TransfigurationFashionEffect.xml", "TransfigurationLevel.xml" }),
        new("Ngoại trang", "Thời trang / Cánh thời trang / Vũ khí ngoại trang", "Logic/FashionManager.cs", new[]{ "Fashion.xml", "FashionTab.xml", "FashionWings.xml", "HorseFashion.xml", "JiaoYinShiZhuangShengJi.xml", "ShiZhuangLevelup.xml", "SpecialTitle.xml", "TransfigurationFashion.xml", "WuQiShiZhuangShengJi.xml" }),
        new("Nhân vật", "Chòm sao (XingZuo)", "Logic/StarConstellationManager.cs", new[]{ "XingZuoType.xml" }),
        new("Nhân vật", "Thiên phú (Talent)", "Logic/Talent/TalentManager.cs", new[]{ "TianFuDian.xml", "TianFuGroupProperty.xml" }),
        new("Nhân vật", "Thành tựu", "Logic/ChengJiuManager.cs", new[]{ "ChengJiuFuWen.xml", "ChengJiuSpecialAttribute.xml" }),
        new("Nhân vật", "Tượng thủ hộ", "Logic/TuJian/GuardStatueManager.cs", new[]{ "JingPoShouHu.xml", "ShouHuLevelUp.xml", "ShouHuSuitUp.xml", "TuJianShouHuType.xml" }),
        new("Nạp/Quỹ", "Nạp tiền / Trực mua (ZhiGou)", "Logic/UserMoneyCharge/UserMoneyMgr.cs", new[]{ "MU_ChongZhi.xml", "ZhiGou.xml" }),
        new("Nạp/Quỹ", "Quỹ (Fund)", "Logic/FundManager.cs", new[]{ "Fund.xml", "FundSet.xml" }),
        new("Phụ bản", "Bản đồ phụ bản", "Logic/FuBenManager.cs", new[]{ "FuBenMap.xml" }),
        new("Phụ bản", "Lang Hồn Yêu Tái", "Logic/CopyWolfManager.cs", new[]{ "LangHunYaoSai.xml" }),
        new("Phụ bản", "Mục tiêu phụ bản", "Logic/CopyTargetManager.cs", new[]{ "FuBenMuBiao.xml" }),
        new("Phụ bản", "Phụ bản Trận pháp LuoLan", "Logic/LuoLanFaZhenCopySceneManager.cs", new[]{ "LuoLanFaZhen.xml" }),
        new("Phụ bản", "Phụ bản Ác ma Laixi", "Logic/EMoLaiXiCopySceneManager.cs", new[]{ "EMoLaiXi.xml", "EMoLaiXiLuXian.xml", "JinBiFuBen.xml" }),
        new("Phụ bản", "Vạn ma hạp cốc", "Logic/WanMoXiaGuManager.cs", new[]{ "WanMoXiaGu.xml" }),
        new("Phụ bản", "Ảo ảnh tự viện / Đền thiên thần", "Logic/HuanYingSiYuanManager.cs", new[]{ "ContinuityKillAward.xml", "HolyGrail.xml", "TempleMirage.xml", "TempleMirageRebirth.xml" }),
        new("Quái vật", "Thông tin quái vật", "Logic/MonsterStaticInfoMgr.cs", new[]{ "Monsters.xml" }),
        new("Sự kiện", "Bài Tarot", "Logic/Tarot/TarotManager.cs", new[]{ "Tarot.xml" }),
        new("Sự kiện", "Hoàn trả Mười", "Logic/TenRetutnManager.cs", new[]{ "TenRetutnAward.xml" }),
        new("Sự kiện", "Hoạt động Mười (Ten)", "Logic/Ten/TenManager.cs", new[]{ "TenAward.xml" }),
        new("Sự kiện", "Mini game (đoán số/lớn nhỏ)", "Logic/BocaiSys/BoCaiConfigMgr.cs", new[]{ "CaiDaXiao.xml", "CaiShuZi.xml", "DaiBiShiYong.xml", "DuiHuanShangCheng.xml" }),
        new("Sự kiện", "Nguyên tố thí luyện", "Logic/ElementWarManager.cs", new[]{ "YuanSuShiLian.xml" }),
        new("Sự kiện", "Phán xét tận thế (MoRi)", "Logic/MoRi/MoRiJudgeManager.cs", new[]{ "MoRiShenPan.xml" }),
        new("Sự kiện", "Tiệc khánh công", "Logic/QingGongYanManager.cs", new[]{ "GleeFeastAward.xml" }),
        new("Sự kiện", "Triệu hồi thú (đào/triệu hồi)", "Logic/CallPetManager.cs", new[]{ "CallPet.xml", "CallPetType.xml", "FreeCallPet.xml", "HuoDongCallPet.xml", "SystemParams.xml", "TeQuanCallPet.xml" }),
        new("Sự kiện", "Truy tìm kho báu (One Piece)", "Logic/OnePiece/OnePieceManager.cs", new[]{ "TreasureBox.xml", "TreasureEvent.xml", "TreasureMap.xml" }),
        new("Sự kiện", "Vòng quay may mắn", "Logic/ZhuanPan/ZhuanPanManager.cs", new[]{ "SystemParams.xml", "ZhuanPan.xml", "ZhuanPanAward.xml" }),
        new("Sự kiện", "Đào càn khôn (New Dig)", "Logic/QianKunManager.cs", new[]{ "FreeNewDig.xml", "HuoDongFreeNewDig.xml", "HuoDongNewDig.xml", "NewDig.xml", "TeQuanFreeNewDig.xml", "TeQuanNewDig.xml" }),
        new("Sự kiện chiến trường", "Chiến trường Zork (sinh tồn)", "Logic/ZorkBattleManager.cs", new[]{ "ZorkAchievement.xml", "ZorkActivityRules.xml", "ZorkDanAward.xml", "ZorkMonster.xml", "ZorkPlayPoint.xml", "ZorkScene.xml" }),
        new("Sự kiện chiến trường", "Chiến trường Đào thoát (Escape)", "Logic/EscapeBattleManager.cs", new[]{ "EscapeActivityRules.xml", "EscapeDanList.xml", "EscapeMapCollection.xml", "EscapeMapSafeArea.xml", "EscapePlayPoint.xml", "EscapeRankAward.xml" }),
        new("Sự kiện thi đấu", "Thế vận hội (đáp đề, đấu giá, mua nhanh)", "Logic/Olympics/OlympicsManager.cs", new[]{ "AoYunAward.xml", "AoYunMatch.xml", "AoYunQiangGou.xml", "AoYunQuestion.xml" }),
        new("Sự kiện thi đấu", "Thế vận hội - Trả lời câu hỏi", "Logic/AoYunDaTi/AoyunDaTiConsts.cs", new[]{ "QuestionAward.xml", "QuestionBank.xml", "QuestionTime.xml" }),
        new("Sự kiện thi đấu", "Vua chiến trường (King Of Battle)", "Logic/KingOfBattleManager.cs", new[]{ "KingOfBattle.xml", "KingOfBattleAward.xml", "KingOfBattleCrystalMonster.xml", "KingOfBattleMonster.xml", "KingOfBattleQiZuo.xml", "KingOfBattleRebirth.xml", "KingOfBattleStore.xml" }),
        new("Thú cưng", "Tinh linh khởi nguyên (Pet)", "Logic/JingLingQiYuanManager.cs", new[]{ "PetGroupProperty.xml", "PetLevelAward.xml", "PetSkillGroupProperty.xml", "PetSkillLevelAward.xml", "PetTianFuAward.xml" }),
        new("Thú cưng", "Tinh linh nguyên tố giác tỉnh", "Logic/JingLingYuanSuJueXingManager.cs", new[]{ "JingLingYuanSu.xml", "JingLingYuanSuShuXing.xml", "SystemParams.xml" }),
        new("Thú cưng", "Yêu tái - BOSS", "Logic/YaoSaiBossManager.cs", new[]{ "PetBoss.xml" }),
        new("Thú cưng", "Yêu tái - Nhiệm vụ", "Logic/YaoSaiMissionManager.cs", new[]{ "PetMission.xml" }),
        new("Thế giới", "Cấp thế giới / Lễ hội theo cấp", "Logic/WorldLevelManager.cs", new[]{ "JieRiLv.xml", "JieRiLvType.xml" }),
        new("Thế giới", "Hệ thống Kỷ nguyên (Era): nhiệm vụ, drop, thưởng, cống hiến", "Logic/EraManager.cs", new[]{ "EraContribution.xml", "EraDrop.xml", "EraReward.xml", "EraTask.xml", "EraUI.xml" }),
        new("Trang bị", "Huy hiệu (Emblem)", "Logic/HuiJiManager.cs", new[]{ "EmblemStar.xml", "EmblemUp.xml" }),
        new("Trang bị", "Hồn thạch (HunShi)", "Logic/FluorescentGem/SoulStoneManager.cs", new[]{ "HunShi.xml", "HunShiExp.xml", "HunShiGoodsType.xml", "HunShiGroup.xml", "HunShiType.xml" }),
        new("Trang bị", "Linh ngọc (LingYu)", "Logic/LingYuManager.cs", new[]{ "LingYuLevelUp.xml", "LingYuSuitUp.xml", "LingYucollect.xml", "LingyuType.xml" }),
        new("Trang bị", "Nguyên tố tim / Tinh luyện (Refine)", "Logic/ElementhrtsManager.cs", new[]{ "ElementsHeart.xml", "Refine.xml", "RefineType.xml" }),
        new("Trang bị", "Phụ ma trang bị (Enchant)", "Logic/FuMo/FuMoManager.cs", new[]{ "EquipEnchantmentExtra.xml", "EquipEnchantmentRandom.xml" }),
        new("Trang bị", "Sách phép Merlin", "Logic/MerlinMagicBook/MerlinMagicBookManager.cs", new[]{ "MagicBook.xml", "MagicBookStar.xml", "MagicWord.xml", "SystemParams.xml" }),
        new("Trang bị", "Thánh thuẫn (Shenshenghudun)", "Logic/ArmorManager.cs", new[]{ "ShenshenghudunJie.xml", "ShenshenghudunXing.xml" }),
        new("Trang bị", "Thần khí / Tái tạo (ZaiZao)", "Logic/ArtifactManager.cs", new[]{ "TaoZhuangProps.xml", "ZaiZao.xml" }),
        new("Trang bị", "Thần ký phù văn", "Logic/ShenJiFuWenManager.cs", new[]{ "ShenJiDian.xml", "ShenJiFuWen.xml" }),
        new("Trang bị", "Trang sức (Ornament)", "Logic/Ornament/OrnamentManager.cs", new[]{ "Ornament.xml", "OrnamentGroup.xml", "OrnamentSite.xml" }),
        new("Trang bị", "Trang sức vũ khí", "Logic/WeaponAdornManager.cs", new[]{ "WeaponAdorn.xml" }),
        new("Trang bị", "Tẩy luyện thuộc tính", "Logic/WashPropsManager.cs", new[]{ "XiLianShuXing.xml", "XiLianType.xml" }),
        new("Trang bị", "Vũ khí đại sư", "Logic/WeaponMaster.cs", new[]{ "WeaponMaster.xml" }),
        new("Trang bị", "Vật phẩm thánh (BuJian/ShengWu)", "Logic/HolyItemManager.cs", new[]{ "BuJian.xml", "ShengWu.xml" }),
        new("Trang bị", "Đào ngọc huỳnh quang", "Logic/FluorescentGem/FluorescentGemManager.cs", new[]{ "GemDig.xml", "GemDigType.xml", "GemLevelup.xml", "SystemParams.xml" }),
        new("Đấu xếp hạng", "Thiên thê (đấu xếp hạng đơn)", "Logic/TianTiManager.cs", new[]{ "DuanWei.xml", "DuanWeiRankAward.xml", "TianTi.xml", "TianTiBirthPoint.xml" }),
        new("Đấu xếp hạng", "Thiên thê 5v5 (đội)", "Logic/TianTi5v5Manager.cs", new[]{ "TeamBattle.xml", "TeamBattleBirthPoint.xml", "TeamDuanWei.xml", "TeamDuanWeiAward.xml" }),
        new("Đấu xếp hạng", "Tranh bá (Match)", "Logic/ZhengBaManager.cs", new[]{ "Match.xml", "MatchAward.xml", "MatchBirthPoint.xml", "Sustain.xml" }),
        new("Đấu xếp hạng", "Tranh bá theo đội", "Logic/ZhanDuiZhengBaManager.cs", new[]{ "TeamMatch.xml", "TeamMatchAward.xml", "TeamMatchBirthPoint.xml" }),
        new("Đấu xếp hạng", "Đấu trường / Quân hàm", "Logic/JingJiChang/JingJiChangManager.cs", new[]{ "JingJi.xml", "JunXian.xml" }),
    };

    public static IEnumerable<IGrouping<string, FeatureItem>> ByCategory() =>
        Items.GroupBy(i => i.Category).OrderBy(g => g.Key);
}
