using System;

namespace HSGameEngine.GameEngine.Logic
{
	public enum ActivityTypes
	{
		None,
		InputFirst,
		InputFanLi,
		InputJiaSong,
		InputKing,
		QiRiKuangHuanLogin = 1,
		QiRiKuangHuanChongZhi,
		QiRiKuangHuanGoal,
		QiRiKuangHuanBuy,
		LevelKing,
		EquipKing,
		HorseKing,
		JingMaiKing,
		JieriDaLiBao,
		JieriDengLuHaoLi,
		JieriVIP,
		JieriCZSong,
		JieriLeiJiCZ,
		JieriZiKa,
		JieriPTXiaoFeiKing,
		JieriPTCZKing,
		JieriBossAttack,
		HeFuDaLiBao = 20,
		HeFuTotalLogin,
		HeFuCZFanLi = 23,
		HeFuPKKing,
		HeFuWanChengKing,
		HeFuBossAttack,
		MeiRiChongZhiHaoLi,
		ChongJiLingQuShenZhuang,
		ShenZhuangJiQingHuiKui,
		XinCZFanLi,
		XingYunChouJiang,
		YuDuZhuanPanChouJiang,
		NewZoneUpLevelMadman,
		NewZoneRechargeKing,
		NewZoneConsumeKing,
		NewZoneBosskillKing,
		NewZoneFanli,
		TotalCharge,
		TotalConsume,
		JieriTotalConsume,
		JieriDuoBei,
		HefuLuolanZhengba = 43,
		OneDollarBuy = 45,
		OneDollarChongZhi,
		InputFanLiNew = 48,
		DanBiChongZhi = 69,
		JieriWing = 53,
		JieriAddon,
		JieriStrengthen,
		JieriAchievement,
		JieriMilitaryRank,
		JieriVIPFanli,
		JieriAmulet,
		JieriArchangel,
		JieriShouli,
		JieriJiehun,
		JieriInputPointsExchg = 64,
		JieRiMeiRiLeiJi = 70,
		JieRiHuiJiFanLi = 75,
		JieRiFuWenFanLi,
		MeiRiChongZhiKing,
		DreamStoneActive = 115,
		ThemeZhiGou = 150,
		ThemeDaLiBao,
		ThemeJingYan,
		ThemeSpec,
		ThemeDuiHuan,
		ThemeBoss,
		ThemeMoYu,
		ThemeZS,
		MaxVal
	}
}
