using System;

namespace HSGameEngine.GameEngine.Logic
{
	public enum DamageType
	{
		DAMAGETYPE_DEFAULT,
		DAMAGETYPE_IGNOREDEFENCE,
		DAMAGETYPE_DOUBLEATTACK,
		DAMAGETYPE_EXCELLENCEATTACK,
		DAMAGETYPE_LUCKYATTACK,
		DAMAGETYPE_THORNDAMAGE,
		DAMAGETYPE_RUTHLESS,
		DAMAGETYPE_COLD,
		DAMAGETYPE_SAVAGE,
		DAMAGETYPE_IGNOREPHY,
		DAMAGETYPE_IGNOREMAGIC,
		RebornCrit,
		DAMAGETYPE_MAX
	}
}
