using System;

namespace HSGameEngine.GameEngine.Logic
{
	public enum ItemCategories
	{
		ItemTask = 50,
		ItemHorsePet = 60,
		ItemBook = 70,
		ItemOther = 80,
		ItemJewel = 90,
		ItemMagic = 100,
		ItemMakings = 110,
		ItemMaterial = 120,
		ItemCurrency,
		ItemDrug = 180,
		ItemAddVal = 230,
		ItemBuffer = 250,
		JingMai,
		WuXue,
		ChengJiu,
		RongYuHuTi = 255,
		ZhanHunHuTi,
		BangQiHuTi = 258,
		HuiJi = 263,
		ItemNormalPack = 301,
		ItemUpPack,
		JueXingSuiPian = 330,
		ZuoQi = 340,
		JiYuanPack = 350,
		YinLiangPack = 401,
		MoneyPack = 501,
		BindMoneyFu = 601,
		TreasureBox = 701,
		GangtieHeart = 800,
		FengnuHeart,
		WangzeHeart,
		JianrenHeart,
		ShouhuHeart,
		QiangzhuangHeart,
		QianggongHeart,
		BuquHeart,
		PingjinHeart,
		JingjueHeart,
		SuiPianHeart,
		WuDiHeart,
		QiJiHeart,
		ZhaoHuanHeart,
		HuanShuHeart,
		ZhanShenHeart,
		YuanSuHeartMax = 815,
		Fashion_Wing = 700,
		Fashion_Title = 702,
		FluorescentDiamond = 901,
		SoulCometStone_Essence = 910,
		SoulCometStone_Fire,
		SoulCometStone_Thurder,
		SoulCometStone_Wind,
		SoulCometStone_Water,
		SoulCometStone_Ice,
		SoulCometStone_Earth,
		SoulCometStone_Guang,
		SoulCometStone_Dian,
		SoulCometStone_Ji,
		SoulCometStone_Leng,
		SoulCometStone_Shuang,
		SoulCometStone_Re,
		SoulCometStone_Bao,
		SoulCometStone_Yun,
		SoulCometStone_Man,
		SoulCometStone_Xue,
		SoulCometStone_Feng,
		SoulCometStone_Chi,
		ChongShengBaoShi = 950,
		ChongShengXuanCai = 960,
		MountHolyStamp = 980,
		MountHolyStampTun,
		TouKui = 0,
		KaiJia,
		HuShou,
		HuTui,
		XueZi,
		XiangLian,
		JieZhi,
		JieHunJieZhi,
		ChiBang,
		ShouHuChong,
		ChongWu,
		WuQi_Jian,
		WuQi_Fu,
		WuQi_Chui,
		WuQi_Gong,
		WuQi_Nu,
		WuQi_Mao,
		WuQi_Zhang,
		WuQi_Dun,
		WuQi_Dao,
		WuQi_GongJianTong,
		WuQi_NuJianTong,
		HuFu,
		Decoration,
		Fashion,
		ShiZhuang_WuQi,
		ShiZhuang_JiaoYin,
		ShiZhuang_ZuoQi,
		BianShen_ShiZhuang,
		TouKui_ChongSheng = 30,
		KaiJia_ChongSheng,
		HuShou_ChongSheng,
		HuTui_ChongSheng,
		XueZi_ChongSheng,
		XiangLian_ChongSheng,
		JieZhi_ChongSheng,
		ShengWu_ChongSheng,
		ShengQi_ChongSheng,
		MaBian = 40,
		HuJu,
		JiangSheng,
		MaAn,
		MaCi,
		MaZhang
	}
}
