using System;

namespace gcloud_voice
{
	public enum GCloudVoiceErr
	{
		GCLOUD_VOICE_SUCC,
		GCLOUD_VOICE_PARAM_NULL = 4097,
		GCLOUD_VOICE_NEED_SETAPPINFO,
		GCLOUD_VOICE_INIT_ERR,
		GCLOUD_VOICE_RECORDING_ERR,
		GCLOUD_VOICE_POLL_BUFF_ERR,
		GCLOUD_VOICE_MODE_STATE_ERR,
		GCLOUD_VOICE_PARAM_INVALID,
		GCLOUD_VOICE_OPENFILE_ERR,
		GCLOUD_VOICE_NEED_INIT,
		GCLOUD_VOICE_ENGINE_ERR,
		GCLOUD_VOICE_POLL_MSG_PARSE_ERR,
		GCLOUD_VOICE_POLL_MSG_NO,
		GCLOUD_VOICE_REALTIME_STATE_ERR = 8193,
		GCLOUD_VOICE_JOIN_ERR,
		GCLOUD_VOICE_QUIT_ROOMNAME_ERR,
		GCLOUD_VOICE_OPENMIC_NOTANCHOR_ERR,
		GCLOUD_VOICE_AUTHKEY_ERR = 12289,
		GCLOUD_VOICE_PATH_ACCESS_ERR,
		GCLOUD_VOICE_PERMISSION_MIC_ERR,
		GCLOUD_VOICE_NEED_AUTHKEY,
		GCLOUD_VOICE_UPLOAD_ERR,
		GCLOUD_VOICE_HTTP_BUSY,
		GCLOUD_VOICE_DOWNLOAD_ERR,
		GCLOUD_VOICE_SPEAKER_ERR,
		GCLOUD_VOICE_TVE_PLAYSOUND_ERR,
		GCLOUD_VOICE_AUTHING,
		GCLOUD_VOICE_INTERNAL_TVE_ERR = 20481,
		GCLOUD_VOICE_INTERNAL_VISIT_ERR,
		GCLOUD_VOICE_INTERNAL_USED,
		GCLOUD_VOICE_BADSERVER = 24577,
		GCLOUD_VOICE_STTING = 28673
	}
}
