using System;

public enum ChouJiangMoneyTypes
{
	None,
	TongQian,
	YinLiang = 8,
	JingYuanZhi = 13,
	JunGongZhi,
	ImpetratePoint,
	LieShaZhi = 20,
	JiFenZhi = 30,
	YuanBao = 40,
	YuanBaoByInput,
	BindYuanBao = 50,
	ZhanHun = 90,
	BangGong = 95,
	LangHunFenMo = 99,
	PetJiFen,
	ZaiZao,
	TianTiRongYao,
	XingHun,
	ShengWang,
	ChengJiu,
	MUMoHe,
	YuanSuFenMo,
	GuardPoint,
	Fluorescent,
	BaoZangJiFen,
	BaoZangXueZuan,
	KingOfBattlePoint,
	StoreTongQian,
	StoreYinLiang,
	Exp,
	RongYu,
	ZhengBaPoint,
	OrnamentCharmPoint = 119,
	ShenLiJingHua,
	Toughness,
	NengLiangSmall,
	NengLiangMedium,
	NengLiangBig,
	NengLiangSuper,
	ShenJiPoints,
	ShenJiJiFen,
	ShenJiJiFenAdd,
	FuWenZhiChen,
	AlchemyElement,
	BHMatchGuessJiFen,
	JueXing,
	JueXingZhiChen,
	EraDonate = 133,
	KuaFuLueDuoEnterNum,
	KuaFuLueDuoEnterNumBuyNum,
	KuaFuLueDuoEnterNumDayID,
	TotalLoginNum,
	CompPoint,
	HunJing,
	MountPoint,
	MoBi,
	YinPiao,
	CompBattleJiFen,
	YuanSuJueXingShi,
	xingyunzhixing = 163
}
