using System;

public enum GongNengIDs
{
	None = -1,
	LianLu = 6,
	HeCheng = 8,
	ZhamMeng = 12,
	MingXiang = 14,
	GuaJi,
	MeiRiBiZuo = 17,
	GamePayerRolePartChiBang = 19,
	JinBiFuBen,
	PaTa,
	GuZhanChang,
	ZuDuiFuBen,
	BaiTan = 2,
	XiLian = 31,
	GamePayerRolePartXingZuo,
	RiChangRenWu = 35,
	ZhuiJia = 37,
	JingYanFuBen,
	TaoFaRenWu = 41,
	PaiHangBang = 10,
	HideTaskBoxJianTou = 10000,
	JingJiChang = 11,
	QiFu = 1,
	ShuiJingHuanJing = 42,
	YuanSuHeart,
	JingLingSystem,
	LieQuYuanSu,
	LingYU = 50,
	ZhuLing,
	ZhuHun,
	ZaiZao = 54,
	ChengJiuFuWen = 53,
	ShengWangXunZhang = 55,
	KuafuHuanyingsiyuan = 57,
	Marray,
	GuardStatue = 60,
	MeiLanZhiShu,
	TianTiJingSai,
	MoriShenPan,
	YuansuShiLian,
	KuafuHuodongBOSS,
	YongZheZhanChang,
	ShengWuXiTong,
	FluorescentDiamond,
	DailyPrivilege,
	LingDI,
	LangHunLingYu,
	SoulCometStonePowder = 73,
	LangHunYaoSai,
	GrowFund,
	JingLingJiNeng,
	PKLovers = 80,
	KuaFuWangZhe = 78,
	ShiPin = 83,
	ZhengDuoZhiDi,
	ShenQiJuHun,
	ZhuanZhi,
	ShenQiSystem,
	JunTuan,
	HuiJiHuTi,
	Alchemy,
	ShenShi = 92,
	JueXing,
	KuaFuPlunderBindding,
	KuaFuPlunder,
	KuaFuWanMoTa,
	Horese,
	Comp,
	ZhuangBeiPeiYang,
	Armor,
	YuanSuJueXing,
	ShenHunFuTi = 103,
	FuMo,
	ChongSheng,
	ChongShengYinJi,
	KuaFuTeamCompete = 108,
	KuaFuTeamCompeteZhengBa = 113,
	MoYuDuoBao,
	DaTaoSha,
	CuiLian,
	MoShenMiBao = 118,
	KuaFuHuoDong = 210,
	RiChangFuBen,
	DuoRenFuBen,
	KuaFuFuBen,
	JingLingJiNengChuanCheng,
	TeamCompeteActivity
}
