using System;

public class MUEventName
{
	public const string CMD_SPR_JUEXING_INFO = "CMD_SPR_JUEXING_INFO";

	public const string CMD_SPR_JUEXING_JIHUO = "CMD_SPR_JUEXING_JIHUO";

	public const string CMD_SPR_JUEXING_TAOCHANGE = "CMD_SPR_JUEXING_TAOCHANGE";

	public const string CMD_SPR_JUEXING_MOHUA = "CMD_SPR_JUEXING_MOHUA";

	public const string CMD_SPR_JUEXING_HUISHOU = "CMD_SPR_JUEXING_HUISHOU";

	public const string CMD_SPR_COMP_DATA = "CMD_SPR_COMP_DATA";

	public const string CMD_SPR_COMP_JOIN = "CMD_SPR_COMP_JOIN";

	public const string CMD_SPR_COMP_RANK_INFO = "CMD_SPR_COMP_RANK_INFO";

	public const string CMD_SPR_COMP_SET_BULLETIN = "CMD_SPR_COMP_SET_BULLETIN";

	public const string CMD_SPR_COMP_SET_ENEMY = "CMD_SPR_COMP_SET_ENEMY";

	public const string CMD_SPR_COMP_ZHIWU = "CMD_SPR_COMP_ZHIWU";

	public const string CMD_SPR_COMP_NOTICE = "CMD_SPR_COMP_NOTICE";

	public const string CMD_SPR_COMP_SIDE_SCORE = "CMD_SPR_COMP_SIDE_SCORE";

	public const string CMD_SPR_COMP_SELF_SCORE = "CMD_SPR_COMP_SELF_SCORE";

	public const string CMD_SPR_COMP_CHANGE_ZHIWU = "CMD_SPR_COMP_CHANGE_ZHIWU";

	public const string CMD_SPR_COMPPOINT_CHANGE = "CMD_SPR_COMPPOINT_CHANGE";

	public const string CMD_SPR_COMP_BATTLE_BASE_DATA = "CMD_SPR_COMP_BATTLE_BASE_DATA";

	public const string CMD_SPR_COMP_BATTLE_CITY_DATA = "CMD_SPR_COMP_BATTLE_CITY_DATA";

	public const string CMD_SPR_COMP_BATTLE_ENTER = "CMD_SPR_COMP_BATTLE_ENTER";

	public const string CMD_SPR_COMP_BATTLE_ENTER_PAIDUI = "CMD_SPR_COMP_BATTLE_ENTER_PAIDUI";

	public const string CMD_SPR_COMP_BATTLE_AWARD = "CMD_SPR_COMP_BATTLE_AWARD";

	public const string CMD_SPR_COMP_BATTLE_STATE = "CMD_SPR_COMP_BATTLE_STATE";

	public const string CMD_SPR_COMP_BATTLE_SIDE_SCORE = "CMD_SPR_COMP_BATTLE_SIDE_SCORE";

	public const string CMD_SPR_COMP_BATTLE_SELF_SCORE = "CMD_SPR_COMP_BATTLE_SELF_SCORE";

	public const string CMD_SPR_COMP_BATTLE_LIANSHA = "CMD_SPR_COMP_BATTLE_LIANSHA";

	public const string CMD_SPR_COMP_BATTLE_STOP_LIANSHA = "CMD_SPR_COMP_BATTLE_STOP_LIANSHA";

	public const string CMD_SPR_COMP_BATTLE_AWARD_GET = "CMD_SPR_COMP_BATTLE_AWARD_GET";

	public const string CMD_DB_BIANSHEN_LEVEL_UP = "CMD_DB_BIANSHEN_LEVEL_UP";

	public const string CMD_SPR_FASHION_FORGE = "CMD_SPR_FASHION_FORGE";

	public const string CMD_SPR_FASHION_EQUIP = "CMD_SPR_FASHION_EQUIP";

	public const string MAIN_ICON_STATE_CHANGE = "MAIN_ICON_STATE_CHANGE";

	public const string CMD_SPR_MINE_BATTLE_SELF_SCORE = "CMD_SPR_MINE_BATTLE_SELF_SCORE";

	public const string CMD_SPR_SPR_GET_KF5V5_INFO = "CMD_SPR_SPR_GET_KF5V5_INFO";

	public const string CMD_SPR_GETFRIENDS = "CMD_SPR_GETFRIENDS";

	public const string CMD_SPR_KF5V5_CREATE_ZHANDUI = "CMD_SPR_KF5V5_CREATE_ZHANDUI";

	public const string CMD_SPR_KF5V5_DELETE_MEMBER = "CMD_SPR_KF5V5_DELETE_MEMBER";

	public const string CMD_SPR_KF5V5_INVITE_TO_ZHANDUI = "CMD_SPR_KF5V5_INVITE_TO_ZHANDUI";

	public const string CMD_SPR_KF5V5_GETZHANDUI_LIST = "CMD_SPR_KF5V5_GETZHANDUI_LIST";

	public const string CMD_SPR_KF5V5_NOTIFY_ZHANDUI_INVITE = "CMD_SPR_KF5V5_NOTIFY_ZHANDUI_INVITE";

	public const string CMD_SPR_KF5V5_AGREE_ZHANDUI_INVITE = "CMD_SPR_KF5V5_AGREE_ZHANDUI_INVITE";

	public const string CMD_SPR_KF5V5_UPDATE_ZHANDUI_XUYAN = "CMD_SPR_KF5V5_UPDATE_ZHANDUI_XUYAN";

	public const string CMD_SPR_KF5V5_REQUEST_TO_ZHANDUI = "CMD_SPR_KF5V5_REQUEST_TO_ZHANDUI";

	public const string CMD_SPR_KF5V5_ROLE_SIGN = "CMD_SPR_KF5V5_ROLE_SIGN";

	public const string CMD_SPR_KF5V5_ROLE_CANCLE_SIGN = "CMD_SPR_KF5V5_ROLE_CANCLE_SIGN";

	public const string CMD_SPR_KF5V5_GET_MY_ZHANDUI_INFO = "CMD_SPR_KF5V5_GET_MY_ZHANDUI_INFO";

	public const string CMD_SPR_KF5V5_NOTIFY_PIPEI_SUCCESS = "CMD_SPR_KF5V5_NOTIFY_PIPEI_SUCCESS";

	public const string CMD_SPR_KF5V5_ENTER_KF5V5_SCENE = "CMD_SPR_KF5V5_ENTER_KF5V5_SCENE";

	public const string CMD_SPR_KF5V5_CHANGE_ZHANDUI_LEADER = "CMD_SPR_KF5V5_CHANGE_ZHANDUI_LEADER";

	public const string CMD_SPR_KF5V5_JIESAN_ZHANDUI = "CMD_SPR_KF5V5_JIESAN_ZHANDUI";

	public const string CMD_SPR_KF5V5_QUERY_DAY_PAIHANG = "CMD_SPR_KF5V5_QUERY_DAY_PAIHANG";

	public const string CMD_SPR_KF5V5_GET_LOG_LIST = "CMD_SPR_KF5V5_GET_LOG_LIST";

	public const string CMD_SPR_KF5V5_QUIT_ZHANDUI = "CMD_SPR_KF5V5_QUIT_ZHANDUI";

	public const string CMD_SPR_KF5V5_BATTLE_RESULT = "CMD_SPR_KF5V5_BATTLE_RESULT";

	public const string CMD_SPR_KF5V5_SIGNUP_STATE = "CMD_SPR_KF5V5_SIGNUP_STATE";

	public const string CMD_SPR_KF5V5_CONFIRM_BATTLE = "CMD_SPR_KF5V5_CONFIRM_BATTLE";

	public const string CMD_SPR_KF5V5_ACCEPT_CONFIRM_BATTLE = "CMD_SPR_KF5V5_ACCEPT_CONFIRM_BATTLE";

	public const string CMD_SPR_KF5V5_Notify_ZHANDUI_DATA_CHANGED = "CMD_SPR_KF5V5_Notify_ZHANDUI_DATA_CHANGED";

	public const string CMD_SPR_REGRESSACTIVE_GETFILE = "CMD_SPR_REGRESSACTIVE_GETFILE";

	public const string CMD_SPR_REGRESSACTIVE_GETSIGNINFO = "CMD_SPR_REGRESSACTIVE_GETSIGNINFO";

	public const string CMD_SPR_REGRESSACTIVE_SING = "CMD_SPR_REGRESSACTIVE_SING";

	public const string CMD_SPR_REGRESSACTIVE_GETSTOREINFO = "CMD_SPR_REGRESSACTIVE_GETSTOREINFO";

	public const string CMD_SPR_REGRESSACTIVE_STOREBUY = "CMD_SPR_REGRESSACTIVE_STOREBUY";

	public const string CMD_SPR_REGRESSACTIVE_INPUTINFO = "CMD_SPR_REGRESSACTIVE_INPUTINFO";

	public const string CMD_SPR_REGRESSACTIVE_INPUT = "CMD_SPR_REGRESSACTIVE_INPUT";

	public const string CMD_SPR_REGRESSACTIVE_ZHIGOU_QUERY = "CMD_SPR_REGRESSACTIVE_ZHIGOU_QUERY";

	public const string CMD_SPR_ZORK_BASE_DATA = "CMD_SPR_ZORK_BASE_DATA";

	public const string CMD_SPR_ZORK_ENTER = "CMD_SPR_ZORK_ENTER";

	public const string CMD_SPR_ZORK_AWARD = "CMD_SPR_ZORK_AWARD";

	public const string CMD_SPR_ZORK_STATE = "CMD_SPR_ZORK_STATE";

	public const string CMD_SPR_ZORK_SIDE_SCORE = "CMD_SPR_ZORK_SIDE_SCORE";

	public const string CMD_SPR_ZORK_RANK_INFO = "CMD_SPR_ZORK_RANK_INFO";

	public const string CMD_SPR_ZORK_LIANSHA = "CMD_SPR_ZORK_LIANSHA";

	public const string CMD_SPR_ZORK_STOP_LIANSHA = "CMD_SPR_ZORK_STOP_LIANSHA";

	public const string CMD_SPR_ZORK_AWARD_GET = "CMD_SPR_ZORK_AWARD_GET";

	public const string CMD_SPR_ZORK_JOIN = "CMD_SPR_ZORK_JOIN";

	public const string CMD_SPR_MAZINGERSTORE_UPGRADE = "CMD_SPR_MAZINGERSTORE_UPGRADE ";

	public const string CMD_SPR_ZHANDUIZHENGBA_MAIN_INFO = "CMD_SPR_ZHANDUIZHENGBA_MAIN_INFO";

	public const string CMD_SPR_ZHANDUIZHENGBA_ZHANDUI_LIST = "CMD_SPR_ZHANDUIZHENGBA_ZHANDUI_LIST";

	public const string CMD_SPR_ZHANDUIZHENGBA_SUPPORT = "CMD_SPR_ZHANDUIZHENGBA_SUPPORT";

	public const string CMD_SPR_ZHANDUIZHENGBA_LOG = "CMD_SPR_ZHANDUIZHENGBA_LOG";

	public const string CMD_SPR_ZHANDUIZHENGBA_ENTER = "CMD_SPR_ZHANDUIZHENGBA_ENTER";

	public const string CMD_SPR_ZHANDUIZHENGBA_SCORE_INFO = "CMD_SPR_ZHANDUIZHENGBA_SCORE_INFO";

	public const string CMD_SPR_ZHANDUIZHENGBA_AWARD = "CMD_SPR_ZHANDUIZHENGBA_AWARD";

	public const string CMD_SPR_ZHANDUIZHENGBA_SUPPORT_LIST = "CMD_SPR_ZHANDUIZHENGBA_SUPPORT_LIST";

	public const string CMD_SPR_ESCAPE_ENTER = "CMD_SPR_ESCAPE_ENTER";

	public const string CMD_SPR_ESCAPE_AWARD = "CMD_SPR_ESCAPE_AWARD";

	public const string CMD_SPR_ESCAPE_STATE = "CMD_SPR_ESCAPE_STATE";

	public const string CMD_SPR_ESCAPE_SIDE_SCORE = "CMD_SPR_ESCAPE_SIDE_SCORE";

	public const string CMD_SPR_ESCAPE_RANK_INFO = "CMD_SPR_ESCAPE_RANK_INFO";

	public const string CMD_SPR_ESCAPE_AWARD_GET = "CMD_SPR_ESCAPE_AWARD_GET";

	public const string CMD_SPR_ESCAPE_JOIN = "CMD_SPR_ESCAPE_JOIN";

	public const string CMD_SPR_ESCAPE_INVITE = "CMD_SPR_ESCAPE_INVITE";

	public const string CMD_SPR_ESCAPE_INVITE_NOTIFY = "CMD_SPR_ESCAPE_INVITE_NOTIFY";

	public const string CMD_SPR_ESCAPE_DEVIL_BUY = "CMD_SPR_ESCAPE_DEVIL_BUY";

	public const string CMD_SPR_ESCAPE_JOIN_INFO = "CMD_SPR_ESCAPE_JOIN_INFO";
}
