using System;
using System.ComponentModel;

public enum RegressActiveOpcode
{
	[Description("成功")]
	RegressActiveSucc = 1,
	[Description("获取活动开启状态错误")]
	RegressActiveOpenErr,
	[Description("不在活动范围内")]
	RegressActiveNotIn,
	[Description("获取最早的注册时间出错")]
	RegressActiveGetRegTime,
	[Description("获取活动归档失败")]
	RegressActiveGetFile,
	[Description("用户信息出错")]
	RegressActiveUserInfoErr,
	[Description("签到验证失败")]
	RegressActiveSignCheckFail,
	[Description("签到记录查询失败")]
	RegressActiveSignSelectFail,
	[Description("获取签到配置出错")]
	RegressActiveSignConfErr,
	[Description("当前活动过期")]
	RegressActiveSignDayErr,
	[Description("获取发放奖励失败")]
	RegressActiveSignGetAwardFail,
	[Description("发放奖励失败")]
	RegressActiveSignGiveAwardFail,
	[Description("重生背包空间不足")]
	RegressActiveSignRebornBagFail,
	[Description("普通背包空间不足")]
	RegressActiveSignBaseBagFail,
	[Description("记录领奖记录失败")]
	RegressActiveSignRecordFail,
	[Description("获取签到信息失败")]
	RegressActiveSignGetInfoFail,
	[Description("没有获取到数据")]
	RegressActiveSignNotInfo,
	[Description("检索类型出错")]
	RegressActiveSignCheckTypeErr,
	[Description("天数计算出错")]
	RegressActiveSignCaleDayErr,
	[Description("已经签到了")]
	RegressActiveSignHas,
	[Description("没到领奖时间")]
	RegressActiveSignNotDay,
	[Description("获取商城配置出错")]
	RegressActiveStoreConfErr,
	[Description("商城验证失败")]
	RegressActiveStoreCheckFail,
	[Description("商城购买物品失败")]
	RegressActiveStoreBuyFail,
	[Description("商城获取天数验证失败")]
	RegressActiveStoreCheckDayFail,
	[Description("商城验证物品失败")]
	RegressActiveStoreCheckGoodFail,
	[Description("商城验证参数出错")]
	RegressActiveStoreCheckParmErr,
	[Description("钻石不足")]
	RegressActiveStoreUserYuanBaoFail,
	[Description("商城记录信息出错")]
	RegressActiveStoreInsertInfoErr,
	[Description("获取充值信息错误")]
	RegressActiveInputGetInfoErr,
	[Description("已经领取过充值奖励了")]
	RegressActiveInputHas,
	[Description("累计充值配置错误")]
	RegressActiveInputConfErr,
	[Description("检查奖励失败")]
	RegressActiveInputCheckAwardErr,
	[Description("发放奖励失败")]
	RegressActiveInputGiveAwardErr,
	[Description("获取直购信息错误")]
	RegressActiveBuyGetInfoErr,
	[Description("获取签到信息错误")]
	RegressActiveGetSignInfoErr,
	[Description("获取签到信息错误")]
	RegressActiveUpdateInputInfoErr
}
