using System;

namespace HSGameEngine.GameFramework.Logic
{
	public enum ActivityTipTypes
	{
		Root,
		MainHuoDongIcon = 1000,
		RiChangHuoDong,
		ShiJieBoss,
		VIPHuoDong,
		ShouFeiBoss,
		HuangJinBoss,
		RiChangHuoDongOther,
		AngelTemple,
		TianTiMonthRankAwards,
		KuafuActivity = 1100,
		MainFuBenIcon = 2000,
		JuQingFuBen,
		ZuDuiFuBen,
		RiChangFuBen,
		KuaFuFuBen,
		FuBenTabs = 2100,
		FuBenItems = 2200,
		MainFuLiIcon = 3000,
		FuLiChongZhiHuiKui,
		ShouCiChongZhi,
		MeiRiChongZhi,
		LeiJiChongZhi,
		LeiJiXiaoFei,
		FuLiMeiRiHuoYue,
		FuLiLianXuDengLu,
		FuLiLeiJiDengLu,
		FuLiMeiRiZaiXian,
		FuLiUpLevelGift,
		ShouCiChongZhi_YiLingQu,
		MeiRiChongZhi_YiLingQu,
		FuLiYueKaFanLi,
		FuLiComBatGift,
		FuLiYueKaFanLi_Award,
		TeamCompeteRequestJoin = 3034,
		TeamCompeteInvite,
		ShenYou,
		FuMo,
		MainJingJiChangIcon = 4000,
		JingJiChangJiangLi,
		JingJiChangJunXian,
		JingJiChangLeftTimes,
		MainGongNeng = 5000,
		MainMingXiangIcon,
		MainEmailIcon,
		MainXinFuIcon = 6000,
		XinFuLevel,
		XinFuKillBoss,
		XinFuChongZhiMoney,
		XinFuUseMoney,
		XinFuFreeGetMoney,
		MainMeiRiBiZuoIcon = 7000,
		ZiYuanZhaoHui,
		MainPaiHang = 7500,
		QiFuIcon = 8000,
		MainChengJiuIcon = 9000,
		MainTopIcon,
		VIPGongNeng = 10000,
		VIPGifts,
		BuChangIcon = 11000,
		ShuiJingHuangJin = 13000,
		ThemeZhiGou = 11501,
		ThemeDaLiBao,
		HeFuActivity = 12000,
		HeFuLogin,
		HeFuTotalLogin,
		HeFuRecharge,
		HeFuPKKing,
		HeFuLuolanZhengba,
		JieRiActivity = 14000,
		JieRiLogin,
		JieRiTotalLogin,
		JieRiDayCZ,
		JieRiLeiJiXF,
		JieRiLeiJiCZ,
		JieRiCZKING,
		JieRiXFKING,
		JieRiGive,
		JieRiGiveKing,
		JieRiRecvKing,
		JieriWing,
		JieriAddon,
		JieriStrengthen,
		JieriAchievement,
		JieriMilitaryRank,
		JieriVIPFanli,
		JieriAmulet,
		JieriArchangel,
		JieriJiehun,
		JieRiLianXuCharge,
		JieRiRecv,
		JieRiIPointsExchg = 14023,
		JieRiSuperDirectBuy,
		JieRiMeiriLeiChong = 14028,
		SpecPActAward = 14115,
		GuildIcon = 15000,
		GuildCopyMap,
		LangHunLingYuIcon,
		LangHunLingYuFightIcon,
		JieRiVIPlibao = 1515,
		JieRiDanBiChongZhi = 14027,
		JieRiHuiJiFanLi = 14033,
		JieRiFuWenFanLi,
		MeiRiChongZhiKing,
		ZhanMengWaiJiaoIconTip = 14111,
		ZhanMengWaiJiaoRequestTip,
		ZhanMengWaiJiaoInfoTip,
		JieRiHongBaoBang = 14032,
		PetBagIcon = 16000,
		CallPetIcon,
		PlayerRecallActivity = 14100,
		Recall_Rewards,
		Recall_GiftSet,
		Recall_SignIn,
		TipSpread = 14105,
		Recall_MyReference = 14104,
		FundChangeLife = 14106,
		FundLogin,
		FundMoney,
		Fund,
		ZhuanXiang,
		EveryDayAct = 14114,
		IDBinging = 14111,
		UserReturnLeiChong = 14115,
		SevenDayActivity = 17000,
		SevenDayLogin,
		SevenDayCharge,
		SevenDayGoal,
		SevenDayBuy,
		SevenDayGoal_1,
		SevenDayGoal_2,
		SevenDayGoal_3,
		SevenDayGoal_4,
		SevenDayGoal_5,
		SevenDayGoal_6,
		SevenDayGoal_7,
		JunTuanRequestIcon = 15005,
		BuildingIcon = 15050,
		OneDollarChongZhi,
		ChaoJiYiYuan,
		JunTuanEra,
		InputFanLiNew,
		ZhengBaCanJoinIcon = 15010,
		CoupleArenaCanAward,
		CoupleWishCanAward,
		TriennialRegressOpen = 15055,
		TriennialRegressSignAward,
		TriennialRegressTotalRechargeAward,
		TriennialRegressDayBuy,
		TriennialRegressStore,
		OlympicsActivity = 20000,
		OlympicsMatch,
		OlympicsGuess,
		AoYunDaTi = 18000,
		XingyunChoujiangIcon = 18002,
		TuJianRedPoint = 19000,
		ZhengDuoFightIcon = 15004,
		JueXingIcon = 18003,
		Reborn = 21000,
		RebornUpgrade,
		MainBag = 30000,
		BagCanUseGoods,
		ZhuangBeiLianLu = 31000,
		ZhuangBeiQiangHua,
		ZhuangBeiZhuiJia,
		ZhuangBeiPeiYang,
		RenWu = 32000,
		RenWuJiNeng,
		RenWuChiBang,
		RenWuXingHun,
		PrivateChat = 90001
	}
}
