using System;

namespace HSGameEngine.GameFramework.Logic
{
	public enum GoodsOwnerTypes
	{
		None = -1,
		SelfBag,
		OtherRole,
		FallGoods,
		Exchange,
		SelfStall,
		OtherStall,
		SelfPet,
		GoodsPack,
		SelfOnSale,
		OtherOnSale,
		AllOthersOnSale,
		WaBaoGoods,
		SysGifts,
		UpgradeEquip,
		OtherRole2,
		ViewTaskInfo,
		YangGongBK,
		QuickEnchance,
		QuickForge,
		ChatGoods,
		EmailFujian,
		NPCSale,
		BaoKuJiangLi,
		mallSale,
		SelfBagNoMenu,
		Lianlu,
		Guide,
		JiaoYiShuo,
		YuansuBag,
		FluorescentDiamondBag,
		SoulCometStoneBag,
		WangZheShangCheng,
		LaoWanJiaShangCheng,
		ZhuanpanGonggao,
		jingLingYaoSai,
		JiYuanShouJi,
		KuaFuPlunderJueXingShop,
		KuaFuPlunderJueXingShop_Diamond,
		ZuoQi,
		ZuoQiCangKu,
		QiangGou,
		LookOther,
		ChongShengLianlu,
		HolyBag,
		HolyBagShengJi,
		HolyBagShengJiXuanZhong
	}
}
