using System;

namespace HSGameEngine.GameFramework.Logic
{
	public enum UIGuanLianTypes
	{
		None = -1,
		WaBao = 10,
		SkillLearn = 20,
		GetHorse = 30,
		GetPet = 40,
		GoodsPack = 50,
		BatchYinPiao = 60,
		OpenYangGong = 70,
		QuickForge = 80,
		QuickEnchance = 90,
		QuickHorseProg = 100,
		QuickJingMai = 110,
		LingLiGuanZhu = 120,
		WaBaoByYaoShi = 140,
		SubForge = 160,
		BornIndexUpdate = 170,
		EquipInherit = 180,
		EnchanceEquip = 190,
		TianShengEquip = 200,
		JunXian = 205,
		QianHuaChuanCheng = 210,
		ShenZhuangLianHua = 220,
		ZaJinDan = 230,
		JingLingZhaoHuan,
		JingLian = 240,
		ZhuangbeiZhuijia = 250,
		ZhuangbeiXilian,
		MengpiaoHecheng = 260,
		ChibangHecheng = 270,
		GuoshiHecheng = 280,
		ShenQiSuiPianHecheng,
		ZuoQiSuiPianHeCheng,
		Tujian = 290,
		Chibang = 300,
		ShengqiZaizao = 310,
		ZhuLing = 320,
		ZhuHun,
		TianFu = 330,
		ShouHuDiaoXiang = 340,
		JuHun,
		MeiLinZhiShu = 350,
		FluorescentDiamond = 360,
		JueXing = 370,
		Shengwu = 380,
		ChengJiu = 801,
		Lingyu = 1350,
		Fashwardrobe = 1480,
		TaLuoPai = 1490,
		Ornament,
		ZHSRoleCreate,
		CangBaoMiJing,
		MoLianZhiDI,
		ShenQiSystem,
		JunTuanCaiJi,
		jingLingYaoSai,
		HuiJiHuTi,
		GloryHall,
		FuWenChouQu = 1501,
		KuaFuPlunderSeverListPart = 1505,
		KuaFuPlunderBiddingPart,
		ActivityCommonSaiShipPin,
		ChangeableRulePart,
		KuaFuPlunderPart,
		KuaFuPlunderSeverInfPart,
		JiYuanPart,
		JueXingShop,
		KuaFuPlunderActionNumberBuy,
		RecyclePart,
		HorsePartZuoQI,
		HorsePartZhangBei,
		HorsePartTUJian,
		ZhangMengMain,
		SheJiaoMain,
		RideQiYuan,
		RideZhuangBeiQiYuan,
		ZhanMengLianSaiJingCai,
		MeiRiBiZuo,
		HorseLieQu,
		FuLiNew,
		ShenShengHuJia,
		YuanSuJueXing,
		YuanSuJueXingNew,
		ShiLiShangCheng,
		ArmorPart,
		ShiLiMiDong,
		ShenHunFuTi,
		ShenHunFuTiShiZhuang,
		KuaFuTeamCompete,
		ActivityTeamCompete,
		RidePetShengYin,
		RidePetShengYinShengJi,
		ChongShengZhuangBeiCuiLian,
		MoShenMiBao,
		UILinkMax = 99999
	}
}
